# c.f. https://www.dash0.com/guides/cadvisor-docker-monitoring
services:
  cadvisor:
    image: ghcr.io/google/cadvisor:0.60.3
    container_name: cadvisor
    network_mode: host
    privileged: true
    pid: host
    command:
      - --port=8081
      - --docker_only=true
      - --housekeeping_interval=2s
      - --disable_metrics=percpu,sched,tcp,udp,diskIO,hugetlb,referenced_memory
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /cgroup:/cgroup:ro
      - /dev/mapper:/dev/mapper:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.13.1
    container_name: prometheus
    network_mode: host
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
      - --web.listen-address=:8082
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    restart: unless-stopped
    depends_on:
      - cadvisor

volumes:
  prometheus_data:
